vpu: fix compiling error with rescue defconfig [1/1]
PD#SWPL-231117

Problem:
common_drivers/drivers/media/common/vpu/vpu_sideband.o: in function `set_vpu_sideband_enable':
(.text+0x82): undefined reference to `disable_side_band'
 common_drivers/drivers/media/common/vpu/vpu_sideband.o: in function `dmc_reg_setting':
(.text+0x5d4): undefined reference to `enable_side_band'

Solution:
add depends on for ddr_tool

Verify:
t6x

Change-Id: Ifa6c5e759259018072ba1ba203e7822d879d70b6
Signed-off-by: Jian Hu <jian.hu@amlogic.com>